---
all:
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_port: 5985
    ansible_winrm_scheme: http
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_become_user: "{{ ansible_user }}"
    ansible_become_method: runas
  hosts:
    database_server:
      ansible_host: 2019base.local
    jenkins_server:
      ansible_host: 2019base.local
    nexus_server:
      ansible_host: 2019base.local
    ccm_server:
      ansible_host: 2019base.local
...